# Generated by Django 4.2.1 on 2023-06-02 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 2)),
        ),
    ]
